// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessageGen.proto

package com.soriole.kademlia.protoc;

public final class ProtoMessage {
  private ProtoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.MessageWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .message.MessageWrapper.MessageType messageType = 1 [default = P2P];</code>
     *
     * <pre>
     * Message fields
     * </pre>
     */
    boolean hasMessageType();
    /**
     * <code>required .message.MessageWrapper.MessageType messageType = 1 [default = P2P];</code>
     *
     * <pre>
     * Message fields
     * </pre>
     */
    com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType getMessageType();

    /**
     * <code>required bytes uidSender = 2;</code>
     */
    boolean hasUidSender();
    /**
     * <code>required bytes uidSender = 2;</code>
     */
    com.google.protobuf.ByteString getUidSender();

    /**
     * <code>required bytes uidReceiver = 3;</code>
     */
    boolean hasUidReceiver();
    /**
     * <code>required bytes uidReceiver = 3;</code>
     */
    com.google.protobuf.ByteString getUidReceiver();

    /**
     * <code>required bytes sessionKey = 4;</code>
     */
    boolean hasSessionKey();
    /**
     * <code>required bytes sessionKey = 4;</code>
     */
    com.google.protobuf.ByteString getSessionKey();

    /**
     * <code>optional bytes messageByte = 5;</code>
     */
    boolean hasMessageByte();
    /**
     * <code>optional bytes messageByte = 5;</code>
     */
    com.google.protobuf.ByteString getMessageByte();

    /**
     * <code>required bytes mac = 6;</code>
     */
    boolean hasMac();
    /**
     * <code>required bytes mac = 6;</code>
     */
    com.google.protobuf.ByteString getMac();
  }
  /**
   * Protobuf type {@code message.MessageWrapper}
   */
  public static final class MessageWrapper extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:message.MessageWrapper)
      MessageWrapperOrBuilder {
    // Use MessageWrapper.newBuilder() to construct.
    private MessageWrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageWrapper(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageWrapper defaultInstance;
    public static MessageWrapper getDefaultInstance() {
      return defaultInstance;
    }

    public MessageWrapper getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType value = com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              uidSender_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              uidReceiver_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              sessionKey_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              messageByte_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              mac_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soriole.kademlia.protoc.ProtoMessage.internal_static_message_MessageWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soriole.kademlia.protoc.ProtoMessage.internal_static_message_MessageWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.class, com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageWrapper> PARSER =
        new com.google.protobuf.AbstractParser<MessageWrapper>() {
      public MessageWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageWrapper(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageWrapper> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code message.MessageWrapper.MessageType}
     *
     * <pre>
     * Message type
     * </pre>
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Client2P = 0;</code>
       */
      Client2P(0, 0),
      /**
       * <code>P2P = 1;</code>
       */
      P2P(1, 1),
      /**
       * <code>P2Client = 2;</code>
       */
      P2Client(2, 2),
      ;

      /**
       * <code>Client2P = 0;</code>
       */
      public static final int Client2P_VALUE = 0;
      /**
       * <code>P2P = 1;</code>
       */
      public static final int P2P_VALUE = 1;
      /**
       * <code>P2Client = 2;</code>
       */
      public static final int P2Client_VALUE = 2;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return Client2P;
          case 1: return P2P;
          case 2: return P2Client;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:message.MessageWrapper.MessageType)
    }

    private int bitField0_;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType messageType_;
    /**
     * <code>required .message.MessageWrapper.MessageType messageType = 1 [default = P2P];</code>
     *
     * <pre>
     * Message fields
     * </pre>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .message.MessageWrapper.MessageType messageType = 1 [default = P2P];</code>
     *
     * <pre>
     * Message fields
     * </pre>
     */
    public com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType getMessageType() {
      return messageType_;
    }

    public static final int UIDSENDER_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString uidSender_;
    /**
     * <code>required bytes uidSender = 2;</code>
     */
    public boolean hasUidSender() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes uidSender = 2;</code>
     */
    public com.google.protobuf.ByteString getUidSender() {
      return uidSender_;
    }

    public static final int UIDRECEIVER_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString uidReceiver_;
    /**
     * <code>required bytes uidReceiver = 3;</code>
     */
    public boolean hasUidReceiver() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes uidReceiver = 3;</code>
     */
    public com.google.protobuf.ByteString getUidReceiver() {
      return uidReceiver_;
    }

    public static final int SESSIONKEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString sessionKey_;
    /**
     * <code>required bytes sessionKey = 4;</code>
     */
    public boolean hasSessionKey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes sessionKey = 4;</code>
     */
    public com.google.protobuf.ByteString getSessionKey() {
      return sessionKey_;
    }

    public static final int MESSAGEBYTE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString messageByte_;
    /**
     * <code>optional bytes messageByte = 5;</code>
     */
    public boolean hasMessageByte() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes messageByte = 5;</code>
     */
    public com.google.protobuf.ByteString getMessageByte() {
      return messageByte_;
    }

    public static final int MAC_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString mac_;
    /**
     * <code>required bytes mac = 6;</code>
     */
    public boolean hasMac() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes mac = 6;</code>
     */
    public com.google.protobuf.ByteString getMac() {
      return mac_;
    }

    private void initFields() {
      messageType_ = com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType.P2P;
      uidSender_ = com.google.protobuf.ByteString.EMPTY;
      uidReceiver_ = com.google.protobuf.ByteString.EMPTY;
      sessionKey_ = com.google.protobuf.ByteString.EMPTY;
      messageByte_ = com.google.protobuf.ByteString.EMPTY;
      mac_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUidSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUidReceiver()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMac()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, uidSender_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, uidReceiver_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, sessionKey_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, messageByte_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, mac_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, uidSender_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, uidReceiver_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, sessionKey_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, messageByte_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, mac_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.MessageWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.MessageWrapper)
        com.soriole.kademlia.protoc.ProtoMessage.MessageWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.soriole.kademlia.protoc.ProtoMessage.internal_static_message_MessageWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.soriole.kademlia.protoc.ProtoMessage.internal_static_message_MessageWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.class, com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.Builder.class);
      }

      // Construct using com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType.P2P;
        bitField0_ = (bitField0_ & ~0x00000001);
        uidSender_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        uidReceiver_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        messageByte_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        mac_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.soriole.kademlia.protoc.ProtoMessage.internal_static_message_MessageWrapper_descriptor;
      }

      public com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper getDefaultInstanceForType() {
        return com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.getDefaultInstance();
      }

      public com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper build() {
        com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper buildPartial() {
        com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper result = new com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uidSender_ = uidSender_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uidReceiver_ = uidReceiver_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sessionKey_ = sessionKey_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.messageByte_ = messageByte_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.mac_ = mac_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper) {
          return mergeFrom((com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper other) {
        if (other == com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasUidSender()) {
          setUidSender(other.getUidSender());
        }
        if (other.hasUidReceiver()) {
          setUidReceiver(other.getUidReceiver());
        }
        if (other.hasSessionKey()) {
          setSessionKey(other.getSessionKey());
        }
        if (other.hasMessageByte()) {
          setMessageByte(other.getMessageByte());
        }
        if (other.hasMac()) {
          setMac(other.getMac());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageType()) {
          
          return false;
        }
        if (!hasUidSender()) {
          
          return false;
        }
        if (!hasUidReceiver()) {
          
          return false;
        }
        if (!hasSessionKey()) {
          
          return false;
        }
        if (!hasMac()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType messageType_ = com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType.P2P;
      /**
       * <code>required .message.MessageWrapper.MessageType messageType = 1 [default = P2P];</code>
       *
       * <pre>
       * Message fields
       * </pre>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .message.MessageWrapper.MessageType messageType = 1 [default = P2P];</code>
       *
       * <pre>
       * Message fields
       * </pre>
       */
      public com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>required .message.MessageWrapper.MessageType messageType = 1 [default = P2P];</code>
       *
       * <pre>
       * Message fields
       * </pre>
       */
      public Builder setMessageType(com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .message.MessageWrapper.MessageType messageType = 1 [default = P2P];</code>
       *
       * <pre>
       * Message fields
       * </pre>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = com.soriole.kademlia.protoc.ProtoMessage.MessageWrapper.MessageType.P2P;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString uidSender_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes uidSender = 2;</code>
       */
      public boolean hasUidSender() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes uidSender = 2;</code>
       */
      public com.google.protobuf.ByteString getUidSender() {
        return uidSender_;
      }
      /**
       * <code>required bytes uidSender = 2;</code>
       */
      public Builder setUidSender(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uidSender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes uidSender = 2;</code>
       */
      public Builder clearUidSender() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uidSender_ = getDefaultInstance().getUidSender();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString uidReceiver_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes uidReceiver = 3;</code>
       */
      public boolean hasUidReceiver() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes uidReceiver = 3;</code>
       */
      public com.google.protobuf.ByteString getUidReceiver() {
        return uidReceiver_;
      }
      /**
       * <code>required bytes uidReceiver = 3;</code>
       */
      public Builder setUidReceiver(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uidReceiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes uidReceiver = 3;</code>
       */
      public Builder clearUidReceiver() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uidReceiver_ = getDefaultInstance().getUidReceiver();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString sessionKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes sessionKey = 4;</code>
       */
      public boolean hasSessionKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes sessionKey = 4;</code>
       */
      public com.google.protobuf.ByteString getSessionKey() {
        return sessionKey_;
      }
      /**
       * <code>required bytes sessionKey = 4;</code>
       */
      public Builder setSessionKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sessionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes sessionKey = 4;</code>
       */
      public Builder clearSessionKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionKey_ = getDefaultInstance().getSessionKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messageByte_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes messageByte = 5;</code>
       */
      public boolean hasMessageByte() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes messageByte = 5;</code>
       */
      public com.google.protobuf.ByteString getMessageByte() {
        return messageByte_;
      }
      /**
       * <code>optional bytes messageByte = 5;</code>
       */
      public Builder setMessageByte(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        messageByte_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes messageByte = 5;</code>
       */
      public Builder clearMessageByte() {
        bitField0_ = (bitField0_ & ~0x00000010);
        messageByte_ = getDefaultInstance().getMessageByte();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes mac = 6;</code>
       */
      public boolean hasMac() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes mac = 6;</code>
       */
      public com.google.protobuf.ByteString getMac() {
        return mac_;
      }
      /**
       * <code>required bytes mac = 6;</code>
       */
      public Builder setMac(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes mac = 6;</code>
       */
      public Builder clearMac() {
        bitField0_ = (bitField0_ & ~0x00000020);
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:message.MessageWrapper)
    }

    static {
      defaultInstance = new MessageWrapper(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:message.MessageWrapper)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MessageWrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_MessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ProtoMessageGen.proto\022\007message\"\341\001\n\016Mes" +
      "sageWrapper\022=\n\013messageType\030\001 \002(\0162#.messa" +
      "ge.MessageWrapper.MessageType:\003P2P\022\021\n\tui" +
      "dSender\030\002 \002(\014\022\023\n\013uidReceiver\030\003 \002(\014\022\022\n\nse" +
      "ssionKey\030\004 \002(\014\022\023\n\013messageByte\030\005 \001(\014\022\013\n\003m" +
      "ac\030\006 \002(\014\"2\n\013MessageType\022\014\n\010Client2P\020\000\022\007\n" +
      "\003P2P\020\001\022\014\n\010P2Client\020\002B+\n\033com.soriole.kade" +
      "mlia.protocB\014ProtoMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_MessageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_MessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_MessageWrapper_descriptor,
        new java.lang.String[] { "MessageType", "UidSender", "UidReceiver", "SessionKey", "MessageByte", "Mac", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
